Cmais\ModelBundle\Entity\AssetAudio:
    type: entity
    table: asset_audio
    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    oneToOne:
        asset:
            targetEntity: Asset
            inversedBy: asset_audio
            joinColumn:
                name: asset_id
                referencedColumnName: id

    fields:
        file:
            type: string
            length: 255
            nullable: true
        original_file:
            type: string
            length: 255
            nullable: true
        original_file_size:
            type: string
            length: 255
            nullable: true
        duration:
            type: string
            length: 255
            nullable: true
        extension:
            type: string
            length: 255
            nullable: true
        year:
            type: string
            length: 255
            nullable: true
        composer:
            type: string
            length: 255
            nullable: true
        interpret:
            type: string
            length: 255
            nullable: true
        label:
            type: string
            length: 255
            nullable: true
        headline:
            type: string
            length: 255
            nullable: true
        genre:
            type: string
            length: 255
            nullable: true
        source:
            type: string
            length: 255
            nullable: true
        author:
            type: string
            length: 255
            nullable: true
