Cmais\ModelBundle\Entity\AssetVideo:
    type: entity
    table: asset_video
    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    oneToOne:
        asset:
            targetEntity: Asset
            inversedBy: asset_video
            joinColumn:
                name: asset_id
                referencedColumnName: id
    oneToMany:
        video_dropboxes:
            targetEntity: VideoDropbox
            mappedBy: asset_video

    fields:
        youtube_id:
            type: string
            length: 255
            nullable: true
        youtube_thumb:
            type: string
            length: 255
            nullable: true
        file:
            type: string
            length: 255
            nullable: true
        original_file:
            type: string
            length: 255
            nullable: true
        original_file_size:
            type: string
            length: 255
            nullable: true
        framerate:
            type: string
            length: 255
            nullable: true
        bitrate:
            type: string
            length: 255
            nullable: true
        duration:
            type: string
            length: 255
            nullable: true
        width:
            type: string
            length: 255
            nullable: true
        height:
            type: string
            length: 255
            nullable: true
        extension:
            type: string
            length: 255
            nullable: true
        headline:
            type: string
            length: 255
            nullable: true
        genre:
            type: string
            length: 255
            nullable: true
        source:
            type: string
            length: 255
            nullable: true
        author:
            type: string
            length: 255
            nullable: true
        is_active:
            type: boolean
            nullable: true
            options:
                default: 0
        is_visible:
            type: boolean
            nullable: true
            options:
                default: 0
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    indexes:
        is_active_index:
            columns: [ is_active ]
        is_visible_index:
            columns: [ is_visible ]
