Cmais\ModelBundle\Entity\AssetAudioGallery:
    type: entity
    table: asset_audio_gallery
    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    oneToOne:
        asset:
            targetEntity: Asset
            inversedBy: asset_audio_gallery
            joinColumn: 
                name: asset_id
                referencedColumnName: id

    fields:
        headline:
            type: string
            length: 255
            nullable: true
        html:
            type: blob
            nullable: true
        genre:
            type: string
            length: 255
            nullable: true
        source:
            type: string
            length: 255
            nullable: true
        author:
            type: string
            length: 255
            nullable: true
