Cmais\ModelBundle\Entity\Asset:
    type: entity
    table: asset
    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    oneToOne:
        asset_content:
            targetEntity: AssetContent
            mappedBy: asset
        asset_image:
            targetEntity: AssetImage
            mappedBy: asset
        asset_video:
            targetEntity: AssetVideo
            mappedBy: asset
        asset_audio:
            targetEntity: AssetAudio
            mappedBy: asset
        asset_file:
            targetEntity: AssetFile
            mappedBy: asset
        asset_image_gallery:
            targetEntity: AssetImageGallery
            mappedBy: asset
        asset_audio_gallery:
            targetEntity: AssetAudioGallery
            mappedBy: asset
        asset_video_gallery:
            targetEntity: AssetVideoGallery
            mappedBy: asset
        asset_question:
            targetEntity: AssetQuestion
            mappedBy: asset
        asset_answer:
            targetEntity: AssetAnswer
            mappedBy: asset
        asset_person:
            targetEntity: AssetPerson
            mappedBy: asset
        asset_schedule:
            targetEntity: AssetSchedule
            mappedBy: asset

    oneToMany:
        categories:
            targetEntity: CategoryAsset
            mappedBy: asset
        sections:
            targetEntity: SectionAsset
            mappedBy: asset
        displays:
            targetEntity: Display
            mappedBy: asset
        parent_assets:
            targetEntity: RelatedAsset
            mappedBy: parent_asset
        related_assets:
            targetEntity: RelatedAsset
            mappedBy: asset
        logs:
            targetEntity: Log
            mappedBy: asset

    manyToOne:
        asset_type:
            targetEntity: AssetType
            inversedBy: assets
            joinColumn:
                name: asset_type_id
                referencedColumnName: id
        site:
            targetEntity: Site
            inversedBy: assets
            joinColumn:
                name: site_id
                referencedColumnName: id
        category:
            targetEntity: Category
            inversedBy: assets
            joinColumn:
                name: category_id
                referencedColumnName: id
        user:
            targetEntity: User
            inversedBy: assets
            joinColumn:
                name: user_id
                referencedColumnName: id

    fields:
        slug:
            type: string
            length: 255
            gedmo:
                slug:
                separator: -
                fields:
                    - title
        title:
            type: string
            length: 255
            nullable: false
        description:
            type: string
            length: 510
            nullable: true
        contact_email:
            type: string
            length: 255
            nullable: true
        position:
            type: integer
            gedmo:
                - sortablePosition
            nullable: true
            options:
                default: 0
        is_active:
            type: boolean
            nullable: true
            options:
                default: 0
        is_visible:
            type: boolean
            nullable: true
            options:
                default: 0
        date_start:
            type: datetime
            nullable: true
        date_end:
            type: datetime
            nullable: true
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    indexes:
        slug_index:
            columns: [ slug ]
        is_active_index:
            columns: [ is_active ]
        is_visible_index:
            columns: [ is_visible ]
