Cmais\ModelBundle\Entity\Block:
    type: entity
    table: block
    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    oneToMany:
        displays:
            targetEntity: Display
            mappedBy: block
        logs:
            targetEntity: Log
            mappedBy: block
    manyToOne:
        section:
            targetEntity: Section
            inversedBy: blocks

    fields:
        slug:
            type: string
            length: 255
            gedmo:
                slug:
                separator: -
                fields:
                    - title
        title:
            type: string
            length: 255
            nullable: false
        description:
            type: string
            length: 510
            nullable: true
        query:
            type: string
            length: 510
            nullable: true
        items:
            type: integer
            nullable: true
            options:
                default: 0
        items_order:
            type: integer
            nullable: true
            options:
                default: 0
        position:
            type: integer
            gedmo:
                - sortablePosition
            nullable: true
            options:
                default: 0
        is_random:
            type: boolean
            nullable: true
            options:
                default: 0
        is_automatic:
            type: boolean
            nullable: true
            options:
                default: 0
        is_active:
            type: boolean
            nullable: true
            options:
                default: 0
        is_visible:
            type: boolean
            nullable: true
            options:
                default: 0
        date_start:
            type: datetime
            nullable: true
        date_end:
            type: datetime
            nullable: true
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    indexes:
        slug_index:
            columns: [ slug ]
        is_active_index:
            columns: [ is_active ]
        is_visible_index:
            columns: [ is_visible ]
        is_random_index:
            columns: [ is_random ]
        is_automatic_index:
            columns: [ is_automatic ]
