Cmais\ModelBundle\Entity\CategoryAsset:
    type: entity
    table: category_asset
    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    manyToOne:
        category:
            targetEntity: Category
            inversedBy: assets
        asset:
            targetEntity: Asset
            inversedBy: categories
