Cmais\ModelBundle\Entity\Display:
    type: entity
    table: display
    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    oneToMany:
        logs:
            targetEntity: Log
            mappedBy: display
    manyToOne:
        block:
            targetEntity: Block
            inversedBy: displays
        asset:
            targetEntity: Asset
            inversedBy: displays

    fields:
        title:
            type: string
            length: 255
            nullable: false
        description:
            type: string
            length: 510
            nullable: true
        label:
            type: string
            length: 255
            nullable: true
        headline:
            type: string
            length: 255
            nullable: true
        url:
            type: string
            length: 255
            nullable: true
        target:
            type: string
            length: 255
            nullable: true
        file:
            type: string
            length: 255
            nullable: true
        image:
            type: string
            length: 255
            nullable: true
        html:
            type: blob
            nullable: true
        position:
            type: integer
            gedmo:
                - sortablePosition
            nullable: true
            options:
                default: 0
        is_active:
            type: boolean
            nullable: true
            options:
                default: 0
        date_start:
            type: datetime
            nullable: true
        date_end:
            type: datetime
            nullable: true
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update

    indexes:
        is_active_index:
            columns: [ is_active ]
