Cmais\ModelBundle\Entity\ImageUsage:
    type: entity
    table: image_usage
    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        slug:
            type: string
            length: 255
            gedmo:
                slug:
                separator: -
                fields:
                    - title
        title:
            type: string
            length: 255
            nullable: false
        description:
            type: string
            length: 510
            nullable: true
        width:
            type: string
            length: 255
            nullable: true
        height:
            type: string
            length: 255
            nullable: true
        background:
            type: string
            length: 255
            nullable: true
        background_color:
            type: string
            length: 255
            nullable: true
        is_active:
            type: boolean
            nullable: true
            options:
                default: 0
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    indexes:
        slug_index:
            columns: [ slug ]
        is_active_index:
            columns: [ is_active ]
