Cmais\ModelBundle\Entity\RelatedAsset:
    type: entity
    table: related_asset
    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    manyToOne:
        parent_asset:
            targetEntity: Asset
            inversedBy: parent_assets
        asset:
            targetEntity: Asset
            inversedBy: related_assets
        related_asset_type:
            targetEntity: RelatedAssetType
            inversedBy: related_assets

    fields:
        position:
            type: integer
            gedmo:
                - sortablePosition
            nullable: true
            options:
                default: 0
        is_active:
            type: boolean
            nullable: true
            options:
                default: 0
        is_visible:
            type: boolean
            nullable: true
            options:
                default: 0

    indexes:
        is_active_index:
            columns: [ is_active ]
        is_visible_index:
            columns: [ is_visible ]
