Cmais\ModelBundle\Entity\RelatedSite:
    type: entity
    table: related_site
    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    manyToOne:
        parent_site:
            targetEntity: Site
            inversedBy: parent_sites
        site:
            targetEntity: Site
            inversedBy: related_sites
        related_site_type:
            targetEntity: RelatedSiteType
            inversedBy: related_sites

    fields:
        position:
            type: integer
            gedmo:
                - sortablePosition
            nullable: true
            options:
                default: 0
        is_active:
            type: boolean
            nullable: true
            options:
                default: 0
        is_visible:
            type: boolean
            nullable: true
            options:
                default: 0

    indexes:
        is_active_index:
            columns: [ is_active ]
        is_visible_index:
            columns: [ is_visible ]
