Cmais\ModelBundle\Entity\Site:
    type: entity
    table: site
    id:
        id:
            type: integer
            generator: { strategy: AUTO }


    manyToOne:
        site_type:
            targetEntity: SiteType
            inversedBy: sites

    oneToMany:
        sections:
            targetEntity: Section
            mappedBy: site
        assets:
            targetEntity: Asset
            mappedBy: site


    fields:
#        site_type_id:
#            type: integer
#            nullable: false
        slug:
            type: string
            length: 255
            gedmo:
                slug:
                separator: -
                fields:
                    - title
        title:
            type: string
            length: 255
            nullable: false
        description:
            type: string
            length: 510
            nullable: true
        url:
            type: string
            length: 255
            nullable: true
        keywords:
            type: string
            length: 255
            nullable: true
        youtube_channel:
            type: string
            length: 255
            nullable: true
        youtube_genre:
            type: string
            length: 255
            nullable: true
        twitter_account:
            type: string
            length: 255
            nullable: true
        twitter_url:
            type: string
            length: 255
            nullable: true
        facebook_account:
            type: string
            length: 255
            nullable: true
        facebook_url:
            type: string
            length: 255
            nullable: true
        googleplus_account:
            type: string
            length: 255
            nullable: true
        googleplus_url:
            type: string
            length: 255
            nullable: true
        image_icon:
            type: string
            length: 255
            nullable: true
        image_thumb:
            type: string
            length: 255
            nullable: true
        image_live:
            type: string
            length: 255
            nullable: true
        contact_email:
            type: string
            length: 255
            nullable: true
        display_order:
            type: integer
            nullable: true
        is_active:
            type: boolean
            nullable: true
            options:
                default: 0
        is_visible:
            type: boolean
            nullable: true
            options:
                default: 0
        date_start:
            type: datetime
            nullable: true
        date_end:
            type: datetime
            nullable: true
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    indexes:
        slug_index:
            columns: [ slug ]
        is_active_index:
            columns: [ is_active ]
        is_visible_index:
            columns: [ is_visible ]


#    manyToOne:
#        SiteType:
#            targetEntity: SiteType
#            inversedBy: Sites
#            joinColumn:
#                name: site_id
#                referencedColumnName: id
