Cmais\ModelBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    oneToMany:
        sites:
            targetEntity: SiteUser
            mappedBy: user
        assets:
            targetEntity: Asset
            mappedBy: user
        logs:
            targetEntity: Log
            mappedBy: user
