Cmais\ModelBundle\Entity\VideoDropbox:
    type: entity
    table: video_dropbox
    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    manyToOne:
        asset_video:
            targetEntity: AssetVideo
            inversedBy: video_dropboxes
        asset_video_gallery:
            targetEntity: AssetVideoGallery
            inversedBy: video_dropboxes

    fields:
        youtube_id:
            type: string
            length: 255
            nullable: true
        action:
            type: string
            length: 255
            nullable: true
        folder:
            type: string
            length: 255
            nullable: true
        status:
            type: string
            length: 255
            nullable: true
        message:
            type: string
            length: 255
            nullable: true
        is_waiting:
            type: boolean
            nullable: true
            options:
                default: 0
        is_pending:
            type: boolean
            nullable: true
            options:
                default: 0
        is_complete:
            type: boolean
            nullable: true
            options:
                default: 0
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    indexes:
        is_waiting_index:
            columns: [ is_waiting ]
        is_pending_index:
            columns: [ is_pending ]
        is_complete_index:
            columns: [ is_complete ]
