parameters:
#    cmais_model.example.class: Cmais\ModelBundle\Example

services:
#    cmais_model.example:
#        class: %cmais_model.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    cmais_model.admin.asset:
        class: Cmais\ModelBundle\Admin\AssetAdmin
        arguments: [~, Cmais\ModelBundle\Entity\Asset, CmaisModelBundle:AssetAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Asset}
